### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by dmaksimovic** [imsnif/synp#14]
I'm afraid I can't share the package-lock.json that I'm trying to convert to yarn.lock, because it's the company's material under protection. It's a big list of dependencies anyway, probably something difficult to handle.

Anyway:
$ synp --source-file ./package-lock.json
Cannot convert undefined or null to object

  Usage: synp [options]

  Options:

    -V, --version                    output the version number
    -s, --source-file [source-file]  The path to the yarn.lock or package-lock.json to be converted
    -h, --help                       output usage information

**Comment by imsnif** [comment]
Hey @dmaksimovic - thanks for opening this issue. While I understand it's problematic to attach the `package.json` and `package-lock.json` files for the reasons you mentioned, it won't really be possible to identify the problem otherwise. Advice and possible workarounds I can offer regardless:

Perform the troubleshooting steps in the readme (specifically removing `node_modules`, reinstalling with yarn and then trying again.

If that doesn't work and you look and see that you have some `github` sourced packages in your package-lock.json, this is a known issue with `synp`. I am waiting to fix it until a specific PR is merged into `yarn` and then will need to rewrite most of `synp` anyway. A rather ugly workaround (my apologies!) can be found here:

https://github.com/imsnif/synp/issues/12

I would be very happy to know if this solved the issue. If not, please also let me know and we'll try to see what we can do without the `package-lock.json` or `package.json` files.
