### ISSUE TITLE
Can this be used without needing multiple package managers installed?

### ISSUE THREAD

**Issue by ZaLiTHkA** [imsnif/synp#40]
I tend to stick with the default `npm` CLI tool for my Node based work, so I don't have other package managers installed (like Yarn, pnpm, etc).

When I found this project, it sounded like something I could use to convert a `yarn.lock` file to `package-lock.json` so that `npm install` had a valid lockfile to work from... But it looks like `synp` is trying to build NPM's lockfile based on the currently installed modules.

Perhaps I'm simply misunderstanding the purpose of this tool, but I assumed from the description that it would allow me to convert a Yarn lockfile to NPM so that I *don't need* to use Yarn at all.. Is this assumption incorrect then?

---

Using [this demo project](https://github.com/MainaWycliffe/demo-for-building-angular-6-library) as a use case..

* Install with `yarn` and the project builds correctly.
* Install with `npm` and the library build fails.
* Convert `yarn.lock` with `synp` after installing with `yarn`, remove `node_modules`, and install with `npm` and the project builds correctly.

>Not sure if this would be helpful at all here, but I did [create a gist](https://gist.github.com/ZaLiTHkA/112a7204c96aeb9b283eaa56c1e9744c) with the demo project's `package.json` and `yarn.lock`, the `package-lock.json` converted by `synp` and generated by `npm`, along with a `diff1 output of the two.

**Comment by imsnif** [comment]
I'm afraid that assumption is incorrect, friend. As mentioned in the readme, synp needs the node_modules installed by the source package manager - it uses them in order to find out the exact structure of the lockfile it needs to build.

It is theoretically possible for this not to be a requirement, but this is not how the tool currently works.

On a different note: I'd recommend using the package manager used by the project you're cloning. Even when using this tool to convert, the conversion is not 100%. It can never be, because the different tools make different assumptions about how the node_modules directory should be built. This can create minor inconsistencies in dependency version resolutions. 

This tool was intended as a one-time use to make the job of a repository maintainer easier if they want to start using another package manager.

**Comment by ZaLiTHkA** [comment]
Ah, ok then.. I must admit, I did actually miss that part of the readme before posting this question, sorry about that.

I guess this is just the curse of the JS world, too many nice things that aren't fully compatible with each other. Pretty sure this tool will still come in handy though, so I am glad I found it. :)
